######################################################################
# Automatically generated by qmake (2.01a) Thu May 9 15:02:34 2024
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h sleeper.h
FORMS += mainwindow.ui
SOURCES += main.cpp mainwindow.cpp
